<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Kaifeng Lu" />

<meta name="date" content="2021-12-15" />

<title>Sample Size Calculation Under Non-Proportional Hazards</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Sample Size Calculation Under
Non-Proportional Hazards</h1>
<h4 class="author">Kaifeng Lu</h4>
<h4 class="date">12/15/2021</h4>



<p>This R Markdown document illustrates the sample size calculation for
a delayed effect model using the lrsamplesize function from lrstat and
verifies the result using the simulation tool.</p>
<p>Suppose that the survival distribution of the control group is
exponential with a median survival time of 13 months. The survival
distribution of the active treatment group is piecewise exponential with
the same hazard rate as the control group for the first 6 months and
with a hazard ratio of 0.58 afterwards. The accrual has a ramp-up period
of 9 months to reach 26 patients per months thereafter, and the total
duration of the enrollment is 22 months. In addition, the annual drop
rate is 5% for each treatment group.</p>
<p>We would like to know the total number of events needed to achieve
80% power for a two-stage group sequential trial with O’Brien-Fleming
spending function and with the interim analysis to be conducted after
observing 80% of the target total number of events. First we load the
packages:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lrstat)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span></code></pre></div>
<p>We use the getDesignGroupSequential function from rpact to find the
stopping boundaries for the planned two-stage group sequential
design.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">design =</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">kMax =</span> <span class="dv">2</span>, <span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="dv">1</span>),</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">alpha =</span> <span class="fl">0.025</span>, <span class="at">typeOfDesign =</span> <span class="st">&quot;asOF&quot;</span>))</span></code></pre></div>
<pre><code>## Design parameters and output of group sequential design:
## 
## User defined parameters:
##   Type of design                               : O&#39;Brien &amp; Fleming type alpha spending 
##   Information rates                            : 0.800, 1.000 
## 
## Derived from user defined parameters:
##   Maximum number of stages                     : 2 
##   Stages                                       : 1, 2 
## 
## Default parameters:
##   Significance level                           : 0.0250 
##   Type II error rate                           : 0.2000 
##   Two-sided power                              : FALSE 
##   Test                                         : one-sided 
##   Tolerance                                    : 1e-08 
##   Type of beta spending                        : none 
## 
## Output:
##   Cumulative alpha spending                    : 0.01221, 0.02500 
##   Critical values                              : 2.250, 2.025 
##   Stage levels (one-sided)                     : 0.01221, 0.02144</code></pre>
<p>Next we use the lrsamplesize function to obtain the follow-up time
and the target number of events.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lrsamplesize</span>(<span class="at">beta =</span> <span class="fl">0.2</span>, <span class="at">kMax =</span> <span class="dv">2</span>, <span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="dv">1</span>),</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">criticalValues =</span> <span class="fu">c</span>(<span class="fl">2.250</span>, <span class="fl">2.025</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">accrualTime =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">9</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">accrualIntensity =</span> <span class="fu">c</span>(<span class="dv">26</span><span class="sc">/</span><span class="dv">9</span><span class="sc">*</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">9</span>), <span class="dv">26</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">piecewiseSurvivalTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">6</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda2 =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>, <span class="dv">2</span>),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">lambda1 =</span> <span class="fu">c</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>, <span class="fl">0.58</span><span class="sc">*</span><span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">gamma1 =</span> <span class="sc">-</span><span class="fu">log</span>(<span class="dv">1</span><span class="fl">-0.05</span>)<span class="sc">/</span><span class="dv">12</span>, <span class="at">gamma2 =</span> <span class="sc">-</span><span class="fu">log</span>(<span class="dv">1</span><span class="fl">-0.05</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">accrualDuration =</span> <span class="dv">22</span>, <span class="at">followupTime =</span> <span class="cn">NA</span>)</span></code></pre></div>
<pre><code>##                          stage 1 stage 2
## informationRates           0.800   1.000
## efficacyBounds             2.250   2.025
## futilityBounds            -6.000   2.025
## cumulativeRejection        0.450   0.800
## cumulativeFutility         0.000   0.200
## cumulativeAlphaSpent       0.012   0.025
## numberOfEvents           252.186 315.232
## numberOfSubjects         468.000 468.000
## analysisTime              31.391  41.519
## efficacyHR                 0.752   0.795
## futilityHR                 2.139   0.795
## efficacyP                  0.012   0.021
## futilityP                  1.000   0.021
## information               62.807  78.025
## HR                         0.765   0.723
## overallReject              0.800        
## alpha                      0.025        
## numberOfEvents           315.232        
## expectedNumberOfEvents   286.840        
## numberOfSubjects         468.000        
## expectedNumberOfSubjects 468.000        
## studyDuration             41.519        
## expectedStudyDuration     36.958        
## accrualDuration           22.000        
## followupTime              19.519        
## fixedFollowup              0.000        
## rho1                       0.000        
## rho2                       0.000</code></pre>
<p>Thus we need to observe 315 events with 468 subjects, and the maximum
study duration is 41.5 months with an expected study duration of 37
months.</p>
<p>To verify this requirement, we resort to the getSimulationSurvival
function from rpact.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getSimulationSurvival</span>(design, <span class="at">directionUpper =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">piecewiseSurvivalTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">6</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">lambda2 =</span> <span class="fu">rep</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>, <span class="dv">2</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">lambda1 =</span> <span class="fu">c</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>, <span class="fl">0.58</span><span class="sc">*</span><span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">13</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">accrualTime =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">9</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">accrualIntensity =</span> <span class="fu">c</span>(<span class="dv">26</span><span class="sc">/</span><span class="dv">9</span><span class="sc">*</span><span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">9</span>), <span class="dv">26</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">dropoutTime =</span> <span class="dv">12</span>, <span class="at">maxNumberOfSubjects =</span> <span class="dv">468</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">plannedEvents =</span> <span class="fu">c</span>(<span class="dv">252</span>, <span class="dv">315</span>),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">maxNumberOfIterations =</span> <span class="dv">10000</span>, <span class="at">seed =</span> <span class="dv">12345</span>)</span></code></pre></div>
<pre><code>## Simulation of survival data (group sequential design):
## 
## Design parameters:
##   Information rates                            : 0.800, 1.000 
##   Critical values                              : 2.250, 2.025 
##   Futility bounds (non-binding)                : -Inf 
##   Cumulative alpha spending                    : 0.01221, 0.02500 
##   Local one-sided significance levels          : 0.01221, 0.02144 
##   Significance level                           : 0.0250 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Maximum number of iterations                 : 10000 
##   Seed                                         : 12345 
##   Direction upper                              : FALSE 
##   Planned cumulative events                    : 252, 315 
##   Maximum number of subjects                   : 468 
##   Accrual time                                 : 1, 2, 3, 4, 5, 6, 7, 8, 9, 22 
##   Accrual intensity                            : 2.9, 5.8, 8.7, 11.6, 14.4, 17.3, 20.2, 23.1, 26.0, 26.0 
##   Drop-out rate (1)                            : 0.050 
##   Drop-out rate (2)                            : 0.050 
##   Piecewise survival times                     : 0, 6 
##   lambda(1)                                    : 0.0533, 0.0309 
##   lambda(2)                                    : 0.0533, 0.0533 
##   Delayed response enabled                     : TRUE 
## 
## Default parameters:
##   Planned allocation ratio                     : 1 
##   Conditional power                            : NA 
##   Drop-out time                                : 12.00 
##   Theta H0                                     : 1 
##   Allocation 1                                 : 1 
##   Allocation 2                                 : 1 
##   kappa                                        : 1 
## 
## Results:
##   Hazard ratio                                 : 1.000, 0.580 
##   Analysis times [1]                           : 31.46 
##   Analysis times [2]                           : 41.24 
##   Expected study duration                      : 36.97 
##   Events not achieved [1]                      : 0.000 
##   Events not achieved [2]                      : 0.000 
##   Number of subjects [1]                       : 468.0 
##   Number of subjects [2]                       : 468.0 
##   Iterations [1]                               : 10000 
##   Iterations [2]                               : 5528 
##   Overall reject                               : 0.7992 
##   Reject per stage [1]                         : 0.4472 
##   Reject per stage [2]                         : 0.3520 
##   Futility stop per stage                      : 0.0000 
##   Early stop                                   : 0.4472 
##   Expected number of subjects                  : 468.0 
##   Expected number of events                    : 286.8 
##   Cumulative number of events [1]              : 252.0 
##   Cumulative number of events [2]              : 315.0 
##   Conditional power (achieved) [1]             : NA 
##   Conditional power (achieved) [2]             : 0.3114 
## 
## Legend:
##   (i): values of treatment arm i
##   [k]: values at stage k</code></pre>
<p>The simulation results confirm the analytic calculations.</p>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
